# ------------------------------------------------------------------------------
# Author:  René Schwaiger (sanssecurs@f-m.fm)
# Date:    2015-01-07
# Version: 1
#
#   Configuration file for [RuboCop](https://github.com/bbatsov/rubocop)
# ------------------------------------------------------------------------------

# Enable most recent rules
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# -- Ruby 1.8 ------------------------------------------------------------------

# We need the following rules to keep compatibility with ruby versions pre 1.9
# shipped with OS X prior to OS X 10.10. The source of the following code is
# http://www.stok.ca/blog/2014/08/24/cleaning.

# Ruby 1.8.7 needs the . on a chain of method calls at the end of a line.
Layout/DotPosition:
  EnforcedStyle: trailing
# Ruby 1.8.7 doesn't have the -> lambda
Style/Lambda:
  Enabled: false
# Ruby 1.8.7 doesn't have 1.9 style hash syntax
Style/HashSyntax:
  EnforcedStyle: hash_rockets
# Ruby 1.8.7 does not support the `positive?` method
Style/NumericPredicate:
  Enabled: false

# -- Common Rules --------------------------------------------------------------

# Allow special characters such as `é` in comments
Style/AsciiComments:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error
