notifications:
  email: sanssecours@me.com

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode10.1

before_install:

  # ============
  # = Homebrew =
  # ============

  - brew update

  # ==========
  # = Python =
  # ==========

  - brew unlink python
  - brew install python || brew upgrade python
  - brew link --overwrite python
  - sudo pip3 install cram flake8 nose tox

  # ========
  # = Ruby =
  # ========

  - rvm use system
  - brew install ruby
  - export PATH="/usr/local/opt/ruby/bin:$PATH"
  - export PATH="$(gem environment gemdir)/bin:$PATH"
  - gem install rubydoctest rubocop

  # ========
  # = Perl =
  # ========

  - curl -L http://cpanmin.us | perl - App::cpanminus
  - export PATH=$PATH:"$HOME/perl5/bin"
  - >
    cpanm --local-lib=~/perl5 local::lib &&
    eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm Perl::Critic

  # =======
  # = TeX =
  # =======

  - curl -L http://tug.org/cgi-bin/mactex-download/BasicTeX.pkg -O
  - sudo installer -pkg BasicTeX.pkg -target /
  - export PATH=$PATH:/Library/TeX/texbin
  - sudo tlmgr update --self --all
  - >-
    sudo tlmgr install
    biber biblatex csquotes ctablestack datatool framed glossaries latexmk
    logreq luacode mfirstuc substr supertabular texdoc texdoctk xfor xstring
  - sudo tlmgr install --with-doc upmethodology

  # ================
  # = Applications =
  # ================

  - brew cask install skim
  - xattr -dr com.apple.quarantine /Applications/Skim.app
  - brew install ghostscript pidof

  # ============
  # = TextMate =
  # ============

  - |
    cd /Applications
    curl -L 'https://api.textmate.org/downloads/release?os=10.9' -o TextMate.tbz
    tar -xvf TextMate.tbz
  - open /Applications/TextMate.app
  - |-
    while ! pidof TextMate | grep -Eq '^[0-9]+[[:space:]]*$'; do
      echo 'Wait until TextMate is open'
      sleep 10
    done

  - mkdir -p "$HOME/bin"
  - cd "$HOME/bin"
  - curl -L http://updates.textmate.org/gtm.bz2 -O
  - bzip2 -d gtm.bz2
  - chmod u+x gtm

  - cd "$HOME/Library/Application Support"
  - mkdir -p TextMate; cd TextMate
  - mkdir -p Managed; cd Managed
  - mkdir -p Bundles; cd Bundles
  - git clone https://github.com/textmate/java.tmbundle.git
  - git clone https://github.com/textmate/javadoc.tmbundle.git
  - git clone https://github.com/textmate/r.tmbundle.git
  - > # Install Bundle Support, if it does not exist yet
    git clone https://github.com/textmate/bundle-support.tmbundle.git
    'Bundle Support.tmbundle' || true

before_script:
  - cd "$TRAVIS_BUILD_DIR"

script:
  - make
